name: Buf CI
on:
  pull_request:
    branches: [ main ]          
  push:
    branches-ignore: [ main ]
    tags-ignore: [ '*' ]
    paths-ignore:
      - '**/*.md'
      - 'docs/**'
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true
permissions:
  contents: read
  pull-requests: write
jobs:
  buf:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: bufbuild/buf-action@v1
        with:
          # Add the parameter token as a secret in your repository settings
          # to authenticate with the Buf Schema Registry.
          setup_only: true
      - uses: actions/setup-go@v5
        with: { go-version: '1.24.x' }
      - run: |
          go install google.golang.org/protobuf/cmd/protoc-gen-go@latest
          go install github.com/twitchtv/twirp/protoc-gen-twirp@latest
          echo "$HOME/go/bin" >> $GITHUB_PATH
      - run: buf build --error-format=github-actions
      - run: buf format -d --exit-code
      - run: buf lint

      # Breaking vs dernier tag (si présent)
      - run: git fetch --tags --force
      - id: prev
        run: echo "tag=$(git describe --tags --abbrev=0 2>/dev/null || true)" >> $GITHUB_OUTPUT
      - if: steps.prev.outputs.tag != ''
        run: buf breaking --against ".git#tag=${{ steps.prev.outputs.tag }}"

      # Génération à blanc (vérifie que les plugins tournent)
      - if: hashFiles('buf.gen.yaml') != ''
        run: buf generate